psaulnie/ft_transcendence

data/backend/src/app.module.ts, data/backend/src/gateway/gateway.ts, data/backend/src/services/users.status.service.ts, data/backend/src/users/users.service.ts
Backend now stores the socket ID of the user, his accessToken, his username and his status in an array.
When the database's done, use it to check if it really is the user performing the action in websockets and profile informations changes
=> dynamic array containing users informations

data/backend/src/chatModule/chat.controller.ts, data/backend/src/entities/room.entity.ts, data/backend/src/entities/usersList.entity.ts, data/backend/src/gateway/gateway.ts, data/backend/src/services/room.service.ts, data/backend/src/users/users.service.ts
fixed:
-block feature
-retrieving rooms when refreshing
-kick & ban feature
=> chat tested and functionnal:

data/backend/src/gateway/gateway.ts, data/backend/src/gateway/hashPasswords.ts, data/backend/src/services/room.service.ts, data/backend/src/services/users.status.service.ts, data/frontend/src/App.tsx, data/frontend/src/components/Chat/Message/Message.tsx, data/frontend/src/components/Chat/Message/UserOptionsMenu.tsx, data/frontend/src/components/Chat/UsersList.tsx, data/frontend/src/components/Global/PrivateRoute.tsx, data/frontend/src/components/Global/UploadButton.tsx, data/frontend/src/components/Login/Login.tsx, data/frontend/src/store/rooms.tsx
- createRoom merged with createPasswordProtectedRoom
- renamed TODOs fetching errors
=> Removed some TODOs

data/frontend/src/webSocket.tsx, docker/frontend/Dockerfile
can't establish connection to ws://localhost:5000/ws
=> fix error websocket

data/backend/src/app.controller.ts, data/backend/src/auth/controller/auth.controller.ts, data/backend/src/gateway/args.types.ts, data/backend/src/gateway/gateway.ts, data/backend/src/services/users.status.service.ts, data/backend/src/users/users.service.ts, data/frontend/src/App.tsx, data/frontend/src/Base.tsx, data/frontend/src/components/Chat/ChatProcess.tsx, data/frontend/src/components/Chat/CreateChannel.tsx, data/frontend/src/components/Chat/Message/InputForm.tsx, data/frontend/src/components/Chat/PasswordDialog.tsx, data/frontend/src/components/Chat/SelectUserDialog.tsx, data/frontend/src/components/Chat/args.interface.tsx, data/frontend/src/components/Chat/args.types.tsx, data/frontend/src/components/Global/Modification.tsx, data/frontend/src/components/Global/Profile.tsx, data/frontend/src/components/Home/Home.tsx, data/frontend/src/components/Navigation/Navigation.tsx, data/frontend/src/store/user.tsx
- change username and all is working
- removed autocomplete of Textfields
- added password type to password TextField
=> Change username done

data/backend/src/gateway/gateway.ts
=> Fix bug usersStatusArray

data/backend/src/gateway/gateway.ts, data/frontend/src/components/Chat/Chat.tsx, data/frontend/src/components/Chat/ChatProcess.tsx, data/frontend/src/components/Chat/CreateChannel.tsx, data/frontend/src/components/Chat/JoinChannel.tsx, data/frontend/src/components/Chat/JoinDirectMessage.tsx, data/frontend/src/components/Chat/Message/UserOptionsMenu.tsx, data/frontend/src/components/Chat/PasswordDialog.tsx, data/frontend/src/components/Chat/RoomOptionsMenu.tsx, data/frontend/src/components/Chat/SelectUserDialog.tsx, data/frontend/src/components/Chat/UsersList.tsx, data/frontend/src/components/Global/Achievements/Achievements.tsx, data/frontend/src/components/Global/ErrorSnackbar.tsx, data/frontend/src/components/Global/Loading.tsx, data/frontend/src/components/Global/PrivateRoute.tsx, data/frontend/src/components/Global/Profile.tsx, data/frontend/src/components/Home/Home.tsx, data/frontend/src/components/Login/Login.tsx, data/frontend/src/components/Navigation/Navigation.tsx, data/frontend/src/index.tsx
- Error snackbar working with reload button, refreshing the website
- Loading component
- Invite user repaired
=> Error & Loading Component

data/backend/src/app.controller.ts, data/backend/src/auth/controller/auth.controller.ts, data/backend/src/chatModule/chat.controller.ts, data/backend/src/entities/room.entity.ts, data/backend/src/entities/stats.entity.ts, data/backend/src/gateway/args.types.ts, data/backend/src/gateway/gateway.ts, data/backend/src/profile.controller.ts, data/backend/src/services/room.service.ts, data/backend/src/users/users.service.ts, data/frontend/src/App.tsx, data/frontend/src/components/Chat/Chat.tsx, data/frontend/src/components/Chat/ChatProcess.tsx, data/frontend/src/components/Chat/CreateChannel.tsx, data/frontend/src/components/Chat/Message/Message.tsx, data/frontend/src/components/Chat/UsersList.tsx, data/frontend/src/components/Chat/args.types.tsx, data/frontend/src/components/Global/ErrorSnackbar.tsx, data/frontend/src/components/Global/Modification.tsx, data/frontend/src/components/Global/Profile.tsx, data/frontend/src/components/Home/Home.tsx, data/frontend/src/components/Navigation/Navigation.tsx, data/frontend/src/store/api.tsx, data/frontend/src/store/user.tsx
- Use RequestWithUser
- Secure route
- GetUserLevel is now GetUserRank
- Removed level from db
- Two users can't have the same username
**Features needing test when the testUser works again**
- Mute user for limited time (5mn)
- Blocked users are removed from the friends list
⚠️ Merge only to main when testUser is working ⚠️
=> Secure controller in backend

data/backend/src/auth/controller/auth.controller.ts, data/frontend/src/components/Global/ErrorSnackbar.tsx
- when the user go back when he's aked to turn on the 2fa, the error is handled
=> Fix error 2fa

data/frontend/src/App.tsx, data/frontend/src/Base.tsx, data/frontend/src/components/Chat/Chat.tsx, data/frontend/src/components/Chat/Room.tsx, data/frontend/src/webSocket.tsx
- on error, the websocket will disconnect
- can't go to 2fa page when not logged in
=> 2fa secure route

data/backend/src/auth/guards/intraAuthGuard.service.ts, data/backend/src/auth/service/auth.service.ts, data/backend/src/chatModule/chat.controller.ts, data/backend/src/gateway/gateway.ts, data/backend/src/users/users.service.ts, data/frontend/src/components/Chat/ChatProcess.tsx, data/frontend/src/components/Chat/UsersList.tsx, data/frontend/src/components/Friendlist/Friendlist.tsx, data/frontend/src/components/Friendlist/inGameStatus.tsx, data/frontend/src/components/Friendlist/offlineStatus.tsx, data/frontend/src/components/Friendlist/onlineStatus.tsx
- fix bug causing the reset of all the relations in user when login in
- fixed friends list
- add friend
- remove friend
- real-time friend page
=> Working friends list

data/backend/src/app.controller.ts, data/backend/src/controllers/profile.controller.ts, data/backend/src/entities/matchHistory.entity.ts, data/backend/src/entities/user.entity.ts, data/backend/src/gateway/gateway.ts, data/backend/src/users/users.service.ts, data/frontend/src/components/Navigation/Navigation.tsx
+ Nav bar will update the user rank when it's fetched from another component
+ Premature close error
=> Fixed avatar corruption & MatchHistory entity

data/frontend/src/components/Achievements/Achievements.tsx
=> achievement page fix

data/frontend/src/components/Game/Matchmaking.tsx
- Progress bar
- Start matchmaking button
- Cancel button
=> Matchmaking page

data/backend/src/gateway/gateway.ts
- Invite to play pong protected with an array knowing if is indeed invited
- Invite to join room protected with an array knowing if is indeed invited 
- Ask being friend protected with an array knowing if is indeed asked for being friend
=> Protect websocket

data/frontend/src/components/Game/Canvas.tsx
- Between a scale of 0.666 & 0.5, the canvas is more centered
=> Improved responsive

data/backend/package-lock.json, data/backend/package.json, data/backend/src/app.controller.ts, data/backend/src/app.module.ts, data/backend/src/auth/auth.module.ts, data/backend/src/chatModule/chat.controller.ts, data/backend/src/game/game.module.ts, data/backend/src/gateway/gateway.ts, data/backend/src/services/game.service.ts, data/backend/src/services/room.service.ts, data/frontend/src/Base.tsx, data/frontend/src/components/Chat/Chat.tsx, data/frontend/src/components/Friendlist/Friendlist.tsx, data/frontend/src/components/Friendlist/inGameStatus.tsx, data/frontend/src/components/Friendlist/offlineStatus.tsx, data/frontend/src/components/Friendlist/onlineStatus.tsx, data/frontend/src/components/Game/Canvas.tsx, data/frontend/src/components/Game/Matchmaking.tsx, data/frontend/src/components/Global/ErrorSnackbar.tsx, data/frontend/src/components/Global/PrivateRoute.tsx, data/frontend/src/components/Home/Home.tsx, data/frontend/src/components/Navigation/Navigation.tsx, data/frontend/src/store/user.tsx
- Removed console.log()
- Removed warning of frontend
- Removed useless variable and function in React Redux
- Added rate limit for API calls
=> Rate limit

data/frontend/src/Base.tsx, data/frontend/src/components/Game/Canvas.css, data/frontend/src/components/Game/Matchmaking.tsx, data/frontend/src/store/user.tsx
- When leaving the matchmaking page, it will cancel the matchmaking
=> Fix matchmaking

data/frontend/src/components/Home/Home.tsx
Remove borderLeft on welcome message
=> Remove borderLeft on welcome message

data/backend/src/gateway/gateway.ts, data/frontend/src/components/Chat/ChatProcess.tsx
- thrown WsException will show an error message
- Explicit error message
=> WsException

data/backend/src/gateway/gateway.ts, data/backend/src/services/room.service.ts
- Bug fixed: “You are now the owner of : room” appearing when already owner and an user leave the room
=> Leave room will no longer tell the owner he is the owner

data/backend/src/chatModule/chat.controller.ts, data/backend/src/gateway/gateway.ts, data/backend/src/services/room.service.ts
- Banned & Muted user can't send msg in a room
- Banned user will not be in room they are banned from when logout/login
=> Banned user can't send msg

data/frontend/src/components/Chat/Message/Message.tsx, data/frontend/src/components/Chat/RoomTabs.tsx
- Add username on chat messages
- Reduce size of active tab in chat to fit tab bar size
=> Add username on chat messages

data/backend/src/chatModule/chat.controller.ts, data/backend/src/gateway/args.types.ts, data/backend/src/gateway/gateway.ts, data/backend/src/services/room.service.ts, data/frontend/src/components/Chat/BanListDialog.tsx, data/frontend/src/components/Chat/ChatProcess.tsx, data/frontend/src/components/Chat/RoomOptionsMenu.tsx, data/frontend/src/components/Chat/args.types.tsx, data/frontend/src/store/api.tsx
- Ban list option for the owner of the room
- Unban button
=> Ban list done & functionnal

data/backend/src/chatModule/chat.controller.ts, data/frontend/src/components/Chat/Message/UserOptionsMenu.tsx
- Bug fixed when a non-owner of the room look for the option menu, unauthorized error because he's not owner
=> Mute fixed

data/frontend/src/components/Chat/BanListDialog.tsx, data/frontend/src/components/Profile/Profile.tsx
- Change a little bit the ban list presentation
- Add usernames on match history
=> Ban list front + matchHistory front

data/backend/src/controllers/profile.controller.ts
Formula now is:
(rank * 10) + (streak * 3) + (winNbr - loseNbr)
=> Leaderboard score fixed

data/backend/src/auth/controller/twoFactorAuth.controller.ts, data/frontend/package-lock.json, data/frontend/package.json, data/frontend/src/Base.tsx, data/frontend/src/components/Global/Settings.tsx, data/frontend/src/components/Login/TwoFactorLogin.tsx, data/frontend/src/components/Navigation/NavDrawer.tsx
- Ask for 2FA validation code before disabling 2FA
=> Disable 2FA

data/backend/src/app.controller.ts, data/backend/src/auth/service/auth.service.ts, data/frontend/src/components/Profile/EditProfile.tsx
- pick a random username until it's not used if already taken
- use high quality 42 intra avatar
=> Random username if already taken

data/backend/src/entities/room.entity.ts, data/backend/src/entities/usersList.entity.ts, data/backend/src/gateway/gateway.ts, data/backend/src/services/room.service.ts
- Added mutedUsers array in DB
- When leaving room while being muted and going back to it, the user will still be muted
=> users muted fixed

data/backend/src/gateway/gateway.ts, data/backend/src/services/game.service.ts, data/frontend/src/components/Game/Canvas.tsx, docker/backend/entrypoint.sh, docker/frontend/entrypoint.sh
=> Finally, fix lag

data/backend/src/gateway/gateway.ts, data/frontend/src/Base.tsx
fix leaving game when navigate or closing the tab
=> fix leaving game

data/backend/src/gateway/gateway.ts, data/frontend/src/components/Chat/CreateChannel.tsx
- Can't create a room with a name length of 0
- Removed alert in createChannel and replaced it with WsExceptions
- Added checks in each websocket function to see if the client sent an argument
=> CreateChannel fixed

data/backend/src/app.module.ts, data/backend/src/gateway/gateway.ts, data/backend/src/services/room.service.ts, data/frontend/src/components/Chat/Chat.tsx, data/frontend/src/components/Global/Settings.tsx, data/frontend/src/components/Login/Login.tsx, data/frontend/src/components/Login/TwoFactorLogin.tsx
- Secure socket for chat
- Secure input for 2FA code
- Fix: simultaneous invitations
=> Remove user test

data/frontend/src/components/Global/Settings.tsx
Enabling 2FA open a dialog window to ask user if he's sure he wants to enable 2FA or cancel
=> Add cancel button when enabling 2FA
